(function (global) {
"use strict";
// Orange Day content data (v1.2 module split) — do not put runtime state here

const CHARACTERS = [
  {
    id: "tiny",
    name: "Tiny Orange Man",
    short: "Tiny",
    color: "#ff8c28",
    accent: "#ffd080",
    silhouette: "round",
    blurb: "Default errand runner. Slip through gaps and climb oversized props.",
    power: "Squeeze",
    powerDesc: "Q near tunnels and tiny gaps to slip through.",
    weakness: "Low crowd influence. Slower voter recruitment.",
    best: "Exploration · delivery · secrets",
    recruitMod: 0.75,
    speed: 118,
    powerKey: "squeeze",
  },
  {
    id: "alex",
    name: "Rally Queen",
    short: "Rally",
    color: "#3ecf8e",
    accent: "#a8ffe0",
    silhouette: "tall",
    blurb: "Local organizer archetype—stages, petitions, crowd energy. Not a national ticket.",
    power: "Rally Cry",
    powerDesc: "Q to pulse a rally. Nearby voters join more easily.",
    weakness: "Stamina dips when big crowds ignore you.",
    best: "Organizing · stage · crowds",
    recruitMod: 1.45,
    speed: 112,
    powerKey: "rally",
  },
  {
    id: "mayor",
    name: "Mayor Mandate",
    short: "Mandate",
    color: "#5b8def",
    accent: "#c8dcff",
    silhouette: "square",
    blurb: "City-hall reform archetype. Local ordinances only—never a presidential run.",
    power: "City Order",
    powerDesc: "Q once: unlock the office or discount the upgrade.",
    weakness: "Overusing rules raises bureaucracy drag.",
    best: "Permits · systems · policy",
    recruitMod: 1.1,
    speed: 105,
    powerKey: "order",
  },
  {
    id: "bernie",
    name: "Bernie Beans",
    short: "Beans",
    color: "#c45c4a",
    accent: "#f0d0c0",
    silhouette: "tall",
    blurb: "Grumpy fairness crusader. Turns excess coins into town buffs.",
    power: "Redistribution",
    powerDesc: "Q: spend ¢ for a short townwide Street buff.",
    weakness: "Slow unless powered by coffee (fix the cart).",
    best: "Fairness · unions · shared buffs",
    recruitMod: 1.2,
    speed: 98,
    powerKey: "redistribute",
  },
  {
    id: "leon",
    name: "Leon Rocket",
    short: "Rocket",
    color: "#60c8e8",
    accent: "#e0f8ff",
    silhouette: "tall",
    blurb: "Eccentric garage inventor—rockets and gadgets, not ballots for president.",
    power: "Launch Mode",
    powerDesc: "Q: rocket dash — speed burst and rooftop hops.",
    weakness: "Crashes can raise Press Heat.",
    best: "Speed · tech · risky shortcuts",
    recruitMod: 1.0,
    speed: 125,
    powerKey: "launch",
  },
  {
    id: "donny",
    name: "Buck Bootstraps",
    short: "Bootstraps",
    color: "#e8c040",
    accent: "#fff0c0",
    silhouette: "square",
    blurb: "Bootstraps memoir author. Pivots positions with heartfelt sincerity.",
    power: "Pivot",
    powerDesc: "Q: publicly reverse a stance — donor cash spike, Heat risk.",
    weakness: "Fact-checkers keep replaying the old clips (Heat).",
    best: "Reinvention · loyalty · donor cash",
    recruitMod: 0.95,
    speed: 108,
    powerKey: "brand",
  },
];

const VOTER_GROUPS = [
  {
    id: "crypto",
    name: "Crypto Bros",
    icon: "₿",
    color: "#f0c040",
    mood: "wired",
    bonus: "+coin from tech/vending tasks",
    preferred: ["tiny", "mayor"],
    rival: "budget",
    passive: { coinMult: 1.15 },
    recruitHint: "Hype a tech gimmick near the vending machine.",
  },
  {
    id: "wine",
    name: "Liberal Wine Moms",
    icon: "🍷",
    color: "#d46aa8",
    mood: "concerned",
    bonus: "+rep from community tasks",
    preferred: ["alex", "mayor"],
    rival: "patriots",
    passive: { repMult: 1.2 },
    recruitHint: "Help at the park or stage with something wholesome.",
  },
  {
    id: "students",
    name: "Student Activists",
    icon: "✊",
    color: "#5ecf7a",
    mood: "fired-up",
    bonus: "Cheaper stamina on protest-style tasks",
    preferred: ["alex"],
    rival: "donors",
    passive: { recruitBoost: 0.15 },
    recruitHint: "Join or start a micro-rally at the civic stage.",
  },
  {
    id: "union",
    name: "Union Workers",
    icon: "🔧",
    color: "#e07040",
    mood: "steady",
    bonus: "Move heavy objects & repairs faster",
    preferred: ["mayor", "alex"],
    rival: "donors",
    passive: { repairBoost: true },
    recruitHint: "Help move the oversized object near the mailbox.",
  },
  {
    id: "moderates",
    name: "Suburban Moderates",
    icon: "🏡",
    color: "#7aa8c8",
    mood: "cautious",
    bonus: "Stabilize rep after chaos",
    preferred: ["mayor", "tiny"],
    rival: "chaos",
    passive: { repShield: 2 },
    recruitHint: "Deliver the permit cleanly. No spectacle required.",
  },
  {
    id: "chaos",
    name: "Chaos Influencers",
    icon: "📡",
    color: "#c060ff",
    mood: "viral",
    bonus: "Amp attention & viral coin spikes",
    preferred: ["tiny", "alex"],
    rival: "moderates",
    passive: { viral: true },
    recruitHint: "Cause a harmless scene at the campaign booth.",
  },
  {
    id: "donors",
    name: "Corporate Donors",
    icon: "💼",
    color: "#5a8aaa",
    mood: "calculating",
    bonus: "Large coin rewards and shop discounts",
    preferred: ["mayor", "tiny"],
    rival: "students",
    passive: { shopDiscount: 0.15, donorBias: true },
    recruitHint: "Flash coins near the vending machine or mayor lobby.",
  },
  {
    id: "conspiracy",
    name: "Conspiracy Podcasters",
    icon: "🎙️",
    color: "#8a6a40",
    mood: "suspicious",
    bonus: "Reveal rumors; sometimes false leads",
    preferred: ["tiny", "bernie"],
    rival: "budget",
    passive: { rumor: true },
    recruitHint: "Poke the alley or tunnel and look like you know secrets.",
  },
  {
    id: "budget",
    name: "Budget Watchers",
    icon: "📊",
    color: "#6a8a6a",
    mood: "austere",
    bonus: "Lower upgrade costs",
    preferred: ["mayor", "bernie"],
    rival: "crypto",
    passive: { cheapUpgrades: true },
    recruitHint: "Buy the tool upgrade thriftily; avoid wasteful spectacle.",
  },
  {
    id: "patriots",
    name: "Die-Hard Patriots",
    icon: "🦅",
    color: "#c04040",
    mood: "fiery",
    bonus: "Rally energy and intimidation",
    preferred: ["donny", "leon"],
    rival: "wine",
    passive: { intimidate: true },
    recruitHint: "Cause spectacle at booth or Media Alley.",
  },
  {
    id: "policy",
    name: "Policy Nerds",
    icon: "📎",
    color: "#7080a0",
    mood: "precise",
    bonus: "Permit and town-hall objectives",
    preferred: ["mayor", "alex"],
    rival: "conspiracy",
    passive: { policy: true },
    recruitHint: "Clean permit runs and Policy Bloc plays.",
  },
  {
    id: "lawn",
    name: "Retired Lawn Guardians",
    icon: "🌿",
    color: "#70a060",
    mood: "watchful",
    bonus: "Report issues; stabilize neighborhoods",
    preferred: ["bernie", "mayor"],
    rival: "chaos",
    passive: { stabilize: true },
    recruitHint: "Keep the park calm; avoid late scandals.",
  },
];

// Phase C districts
const DISTRICTS = [
  { id: "plaza", name: "Town Hall Plaza", unlockDay: 1, color: "#ffb347" },
  { id: "media", name: "Media Alley", unlockDay: 2, color: "#c060ff" },
  { id: "campus", name: "Campus Green", unlockDay: 3, color: "#5ecf7a" },
  { id: "donor", name: "Donor Heights", unlockDay: 4, color: "#e8c040" },
];

// Named coalitions (Phase B) — match 2 of 3 for partial, 3 of 3 for full
const COALITIONS = [
  {
    id: "grassroots",
    name: "Grassroots Coalition",
    members: ["students", "union", "wine"],
    bonus: "Faster repairs · +Street Cred gains",
    drawback: "Shops cost more",
    color: "#5ecf7a",
  },
  {
    id: "money",
    name: "Money Machine",
    members: ["crypto", "donors", "moderates"],
    bonus: "More coins · better shop prices",
    drawback: "Scandal risk (+Press Heat)",
    color: "#f0c040",
  },
  {
    id: "chaos_ticket",
    name: "Chaos Ticket",
    members: ["chaos", "conspiracy", "patriots"],
    bonus: "Viral coin spikes · bold checks",
    drawback: "Random plaza noise",
    color: "#c060ff",
  },
  {
    id: "policy",
    name: "Policy Bloc",
    members: ["budget", "moderates", "policy"],
    bonus: "Cheaper upgrades · permit ease",
    drawback: "Slower voter recruitment",
    color: "#7aa8c8",
  },
];

// Daily civic rule cards — 7-day cycle (+ 1.1 extras cycled in)
const BOARD_RULES = [
  { id: "open_mic", title: "Open Mic Day", blurb: "Stage energy high. Recruit near STAGE improves.", recruitNearStage: 0.2 },
  { id: "austerity", title: "Austerity Memo", blurb: "Upgrades cheaper; coin pickups thinner.", upgradeMult: 0.85, coinMult: 0.9 },
  { id: "press_pool", title: "Press Pool Roaming", blurb: "Cameras everywhere. Heat rises faster.", heatMult: 1.5 },
  { id: "union_friendly", title: "Labor Listening Hour", blurb: "Repair and heavy lifts pay better Street.", streetBoost: 1.2 },
  { id: "donor_day", title: "Donor Courtyard Open", blurb: "Donor Heights buzz. Coin mult up; Heat risk.", coinMult: 1.15, heatMult: 1.2 },
  { id: "quiet_hours", title: "Quiet Hours Ordinance", blurb: "Chaos quieter. Recruit slower; Heat dampened.", recruitNearStage: -0.05, heatMult: 0.7 },
  { id: "election_eve", title: "Election Eve Watch", blurb: "Everything counts double toward endings.", coinMult: 1.1, heatMult: 1.2 },
  // 1.1 seasonal / micro rules (appear when day wraps past 7 or mixed in by index)
  { id: "farmers_market", title: "Farmers Market", blurb: "Park energy up. Street gains feel juicier.", streetBoost: 1.25, coinMult: 1.05 },
  { id: "pothole_week", title: "Pothole Week", blurb: "Repairs matter. Coffee/cart fixes pay more Street.", streetBoost: 1.3 },
  { id: "influencer_influx", title: "Influencer Influx", blurb: "Viral odds up; Heat creeps faster.", heatMult: 1.35, coinMult: 1.1 },
];

// Mid-day micro-events (1.1) — toast + small axis/coin nudge once per day max
const MICRO_EVENTS = [
  { id: "duck_caucus", text: "Park ducks form a caucus. +1 Street for noticing.", axes: { street: 1 } },
  { id: "lost_mic", text: "Someone drops a mic. You return it. +1 Donor goodwill.", axes: { donor: 1 } },
  { id: "viral_clip", text: "A clip of you goes mildly viral. +2 Heat, +3¢.", axes: { heat: 2 }, coins: 3 },
  { id: "budget_memo", text: "Anonymous budget memo praises thrift. +1 Donor.", axes: { donor: 1 } },
  { id: "lawn_tip", text: "A Lawn Guardian tips you off. Codex whisper.", axes: { street: 1 } },
];

const POWER_RANK_COST = [0, 18, 36, 55]; // v1.0: reachable within a week

const OBJECTIVES = [
  { id: "permit", label: "Deliver lost permit to Town Hall", short: "Deliver permit", target: 1 },
  { id: "buttons", label: "Collect 3 campaign buttons", short: "3 campaign buttons", target: 3 },
  { id: "coffee", label: "Fix the broken coffee cart", short: "Fix coffee cart", target: 1 },
  { id: "voters", label: "Recruit 3 voter groups", short: "Recruit 3 voters", target: 3 },
  { id: "home", label: "Return home before night", short: "Home before night", target: 1 },
];

// Phase C crises (7-day election week)
const CRISES = [
  { day: 1, id: "permit_panic", title: "PERMIT PANIC", blurb: "Lost paperwork clogs the plaza.", coinMult: 1.1, recruitMod: 0, buttonCost: 4, upgradeMult: 1 },
  { day: 2, id: "button_market", title: "BUTTON BLACK MARKET", blurb: "Merch scarce; debates heat up.", coinMult: 1, recruitMod: 0.05, buttonCost: 6, upgradeMult: 1, debateDay: true },
  { day: 3, id: "caffeine_collapse", title: "CAFFEINE COLLAPSE", blurb: "Fix the cart; democracy runs on drip.", coinMult: 1.05, recruitMod: 0, buttonCost: 4, upgradeMult: 0.9, scandalDay: true },
  { day: 4, id: "march_monday", title: "MARCH MONDAY", blurb: "Campus stirs. Union energy rises.", coinMult: 1, recruitMod: 0.08, buttonCost: 4, upgradeMult: 1, marchDay: true },
  { day: 5, id: "gala_glow", title: "GALA GLOW", blurb: "Donor Heights sparkles. Velvet ropes.", coinMult: 1.15, recruitMod: 0, buttonCost: 5, upgradeMult: 1.05, galaDay: true },
  { day: 6, id: "spin_storm", title: "SPIN STORM", blurb: "Media Alley floods the feeds.", coinMult: 1.05, recruitMod: 0.05, buttonCost: 5, upgradeMult: 1, heatMult: 1.3 },
  { day: 7, id: "election_eve", title: "ELECTION EVE", blurb: "Last day before the count. Everything matters.", coinMult: 1.1, recruitMod: 0.05, buttonCost: 4, upgradeMult: 0.95 },
];

// Stitched multi-district map (Phase C)
const MAP_W = 2200;
const MAP_H = 1100;

const ZONES = [
  // —— Town Hall Plaza (existing) ——
  { id: "home", name: "Tiny Home", x: 70, y: 90, w: 110, h: 90, color: "#c4783a", label: "HOME", district: "plaza" },
  { id: "board", name: "Town Board", x: 220, y: 70, w: 100, h: 70, color: "#6b5a3a", label: "BOARD", district: "plaza" },
  { id: "mayor", name: "Mayor's Office", x: 380, y: 50, w: 160, h: 110, color: "#4a6a9a", label: "MAYOR", district: "plaza" },
  { id: "locked", name: "Locked Office", x: 560, y: 55, w: 90, h: 90, color: "#3a3a55", label: "LOCKED", district: "plaza" },
  { id: "coffee", name: "Coffee Cart", x: 90, y: 260, w: 100, h: 80, color: "#8b5a3a", label: "COFFEE", district: "plaza" },
  { id: "mailbox", name: "Oversized Mailbox", x: 250, y: 240, w: 120, h: 110, color: "#3a6a8a", label: "MAIL", district: "plaza" },
  { id: "vending", name: "Vending Machine", x: 430, y: 250, w: 90, h: 100, color: "#5a7a5a", label: "VEND", district: "plaza" },
  { id: "alley", name: "Alley Shortcut", x: 580, y: 230, w: 70, h: 140, color: "#2a2a38", label: "ALLEY", district: "plaza" },
  { id: "stage", name: "Civic Stage", x: 720, y: 80, w: 160, h: 100, color: "#9a4a6a", label: "STAGE", district: "plaza" },
  { id: "booth", name: "Campaign Booth", x: 720, y: 230, w: 130, h: 90, color: "#c04040", label: "BOOTH", district: "plaza" },
  { id: "park", name: "Small Park", x: 880, y: 200, w: 140, h: 160, color: "#3a8a50", label: "PARK", district: "plaza" },
  { id: "tunnel", name: "Hidden Tunnel", x: 90, y: 420, w: 80, h: 50, color: "#1a2830", label: "TUNNEL", district: "plaza" },
  { id: "plaza", name: "Fountain Plaza", x: 380, y: 420, w: 200, h: 140, color: "#5a8aaa", label: "PLAZA", district: "plaza" },
  { id: "crate", name: "Oversized Crate", x: 250, y: 400, w: 90, h: 70, color: "#8a6a40", label: "CRATE", district: "plaza" },
  { id: "boelunch", name: "Board of Ed Lunch Table", x: 380, y: 190, w: 90, h: 50, color: "#7a6a30", label: "LUNCH", district: "plaza" },
  // gates from plaza
  { id: "gate_media", name: "Gate → Media", x: 1000, y: 300, w: 70, h: 80, color: "#6a3080", label: "→MEDIA", district: "plaza", transit: "media" },
  { id: "gate_campus", name: "Gate → Campus", x: 480, y: 620, w: 90, h: 60, color: "#308050", label: "→CAMPUS", district: "plaza", transit: "campus" },
  // —— Media Alley (east) ——
  { id: "studio", name: "Spin Studio", x: 1280, y: 120, w: 140, h: 100, color: "#7a40a0", label: "STUDIO", district: "media" },
  { id: "cameras", name: "Camera Nest", x: 1480, y: 200, w: 110, h: 90, color: "#5a3070", label: "CAMS", district: "media" },
  { id: "leakdesk", name: "Leak Desk", x: 1350, y: 360, w: 120, h: 80, color: "#904060", label: "LEAK", district: "media" },
  { id: "addesk", name: "Ad Sales Desk", x: 1550, y: 360, w: 110, h: 80, color: "#a05880", label: "AD $", district: "media" },
  { id: "gate_plaza_m", name: "Gate → Plaza", x: 1120, y: 300, w: 70, h: 80, color: "#c4783a", label: "→PLAZA", district: "media", transit: "plaza" },
  { id: "gate_donor_m", name: "Gate → Donors", x: 1680, y: 180, w: 70, h: 70, color: "#c0a030", label: "→DONOR", district: "media", transit: "donor" },
  // —— Campus Green (south) ——
  { id: "quad", name: "Campus Quad", x: 400, y: 780, w: 180, h: 120, color: "#3a9a50", label: "QUAD", district: "campus" },
  { id: "petition", name: "Petition Table", x: 220, y: 820, w: 100, h: 70, color: "#50b070", label: "PETITION", district: "campus" },
  { id: "march", name: "March Route", x: 640, y: 800, w: 140, h: 90, color: "#e07040", label: "MARCH", district: "campus" },
  { id: "gate_plaza_c", name: "Gate → Plaza", x: 480, y: 700, w: 90, h: 50, color: "#c4783a", label: "→PLAZA", district: "campus", transit: "plaza" },
  // —— Donor Heights (northeast) ——
  { id: "velvet", name: "Velvet Rope", x: 1750, y: 80, w: 100, h: 70, color: "#a08030", label: "ROPE", district: "donor" },
  { id: "gala", name: "Gala Ballroom", x: 1900, y: 120, w: 160, h: 110, color: "#d4b040", label: "GALA", district: "donor" },
  { id: "pitch", name: "Pitch Pavilion", x: 1800, y: 280, w: 130, h: 90, color: "#c0a050", label: "PITCH", district: "donor" },
  { id: "gate_media_d", name: "Gate → Media", x: 1680, y: 100, w: 60, h: 60, color: "#6a3080", label: "→MEDIA", district: "donor", transit: "media" },
];

const DISTRICT_SPAWNS = {
  plaza: { x: 120, y: 140 },
  media: { x: 1250, y: 280 },
  campus: { x: 480, y: 760 },
  donor: { x: 1820, y: 200 },
};

const WALLS = [
  // outer fence soft bounds handled by clamp; internal blockers
  { x: 560, y: 55, w: 90, h: 20 }, // locked front until opened
];

// Decorative plaza clutter (drawn + Y-sorted feel; non-blocking)
const CLUTTER = [
  { key: "clutter/bench", x: 160, y: 200, w: 56, h: 32 },
  { key: "clutter/bench", x: 620, y: 400, w: 56, h: 32 },
  { key: "clutter/bench", x: 920, y: 360, w: 52, h: 30 },
  { key: "clutter/sign", x: 340, y: 175, w: 28, h: 44 },
  { key: "clutter/sign", x: 680, y: 200, w: 28, h: 44 },
  { key: "clutter/poster", x: 200, y: 155, w: 26, h: 32 },
  { key: "clutter/poster", x: 540, y: 200, w: 26, h: 32 },
  { key: "clutter/poster", x: 760, y: 195, w: 26, h: 32 },
  { key: "clutter/lamp", x: 300, y: 160, w: 22, h: 52 },
  { key: "clutter/lamp", x: 700, y: 360, w: 22, h: 52 },
  { key: "clutter/lamp", x: 500, y: 400, w: 22, h: 52 },
  { key: "clutter/bin", x: 400, y: 210, w: 26, h: 34 },
  { key: "clutter/bin", x: 820, y: 280, w: 26, h: 34 },
  { key: "clutter/flower", x: 140, y: 350, w: 22, h: 26 },
  { key: "clutter/flower", x: 960, y: 300, w: 22, h: 26 },
  { key: "clutter/flower", x: 480, y: 520, w: 22, h: 26 },
  { key: "clutter/newspaper", x: 370, y: 390, w: 28, h: 18 },
  { key: "clutter/newspaper", x: 600, y: 470, w: 28, h: 18 },
  { key: "clutter/pigeon", x: 420, y: 455, w: 24, h: 20, bob: true },
  { key: "clutter/pigeon", x: 780, y: 320, w: 24, h: 20, bob: true },
  { key: "clutter/pigeon", x: 250, y: 210, w: 22, h: 18, bob: true },
  { key: "clutter/pigeon", x: 900, y: 250, w: 22, h: 18, bob: true },
];

const NPCS = [
  {
    id: "clerk",
    name: "Permit Clerk Pip",
    x: 450,
    y: 120,
    color: "#d0c8a0",
    home: "mayor",
    lines: {
      default: "Lost permits find their way home. Usually.",
      permit: "That's the missing civic stamp! You're a municipal hero.",
      done: "Town Hall is slightly less cursed today. Slightly.",
    },
  },
  {
    id: "barista",
    name: "Barista Bean",
    x: 140,
    y: 300,
    color: "#a07050",
    home: "coffee",
    lines: {
      default: "Cart's broken. Democracy runs on caffeine, kid.",
      fix: "You fixed it! Free drip of civic courage.",
      done: "Steaming. Literally and politically.",
    },
  },
  {
    id: "vendor",
    name: "Vend-o-Rama",
    x: 475,
    y: 300,
    color: "#70a070",
    home: "vending",
    lines: {
      default: "INSERT COINS · DISPENSE BUTTONS · NO REFUNDS",
      buy: "Clunk. A shiny campaign button appears. Artisanal.",
    },
  },
  {
    id: "paver",
    name: "Paver Pete",
    x: 740,
    y: 430,
    color: "#8a8a95",
    home: "plaza",
    lines: {
      default: "These potholes? Criminal. 10¢ and my guys get right on it.",
      broke: "No coins, no asphalt dreams. Come back with 10¢.",
      excuses: ["Supply chain. Nothing moves.", "Permit's pending. Any decade now.", "My asphalt guy's cousin has the truck.", "We did a study. The study needs a study."],
      exposed: "Look, the potholes are a JOURNEY, not a destination.",
    },
  },
  {
    id: "mover",
    name: "Foreman Flo",
    x: 295,
    y: 430,
    color: "#e08050",
    home: "crate",
    lines: {
      default: "This crate is an entire zoning dispute. Help me shove it?",
      help: "Teamwork! Union strength is not a metaphor today.",
      done: "Path's clear. Remember who moved the city.",
    },
  },
  {
    id: "stagehand",
    name: "Stagehand Sky",
    x: 800,
    y: 140,
    color: "#e090b0",
    home: "stage",
    lines: {
      default: "Mic check for democracy? Anyone?",
      rally: "That rally hit. Students are nodding like it's a syllabus.",
    },
  },
  {
    id: "boothie",
    name: "Booth Intern Brynn",
    x: 780,
    y: 275,
    color: "#f07070",
    home: "booth",
    lines: {
      default: "Free buttons if you pose with the cardboard candidate.",
      chaos: "That was… content. The algorithm will feast.",
    },
  },
  {
    id: "parkgoer",
    name: "Park Regular Pat",
    x: 950,
    y: 280,
    color: "#80c090",
    home: "park",
    lines: {
      default: "Quiet green space. Please don't legislate the ducks.",
      wine: "You brought actual kindness. The wine-moms approve.",
    },
  },
  {
    id: "watchdog",
    name: "Budget Owl",
    x: 270,
    y: 105,
    color: "#c0a060",
    home: "board",
    lines: {
      default: "Read the board. Then question the board. Then rest.",
    },
    dayLines: {
      1: "Day one: the board is already lying by omission.",
      4: "Midweek: loyalty is a budget line item.",
      7: "Election eve: count twice, trust once.",
    },
  },
  {
    id: "anchor",
    name: "Anchor Remy",
    x: 1340,
    y: 180,
    color: "#c080e0",
    home: "studio",
    lines: { default: "Live in five. Make it punchy. Make it vague." },
    dayLines: {
      2: "Media Alley opens — bring a narrative or become one.",
      3: "Leak season. Don't trip over your own soundbite.",
      6: "Spin storm: every errand is content.",
    },
  },
  {
    id: "leaker",
    name: "Source Q",
    x: 1400,
    y: 400,
    color: "#a06070",
    home: "leakdesk",
    lines: { default: "I have documents. Also vibes. Mostly vibes." },
    dayLines: {
      3: "Scandal-ready. Interact for a LEAK setpiece when the board says so.",
      5: "Gala photoshoot needs a villain. Don't volunteer.",
    },
  },
  {
    id: "ra",
    name: "RA Jules",
    x: 480,
    y: 840,
    color: "#60d080",
    home: "quad",
    lines: { default: "Quad rules: no drones, no donor balloons, yes petitions." },
    dayLines: {
      3: "Campus is open. Petition hard, sleep harder.",
      4: "March Monday — the route wants feet.",
      7: "Students vote with feet and group chats.",
    },
  },
  {
    id: "host",
    name: "Host Celeste",
    x: 1960,
    y: 180,
    color: "#e8d080",
    home: "gala",
    lines: { default: "Invitation optional. Confidence mandatory." },
    dayLines: {
      4: "Donor Heights unlocks. Smile with your tax policy.",
      5: "Gala night. Branding optional. Heat inevitable.",
      7: "They count ballots; we count canapés.",
    },
  },
];

// Pickup / button spots (spread across districts)
const BUTTON_SPOTS = [
  { x: 760, y: 260, taken: false },
  { x: 500, y: 480, taken: false },
  { x: 200, y: 180, taken: false },
  { x: 900, y: 120, taken: false },
  { x: 1450, y: 250, taken: false },
  { x: 500, y: 850, taken: false },
  { x: 1920, y: 220, taken: false },
];

global.ORANGE_DATA = {
  CHARACTERS,
  VOTER_GROUPS,
  DISTRICTS,
  COALITIONS,
  BOARD_RULES,
  MICRO_EVENTS,
  POWER_RANK_COST,
  OBJECTIVES,
  CRISES,
  MAP_W,
  MAP_H,
  ZONES,
  DISTRICT_SPAWNS,
  CLUTTER,
  NPCS,
  BUTTON_SPOTS,
};
})(typeof window !== "undefined" ? window : globalThis);
